<a href="https://colab.research.google.com/github/69-LaxmiArsul/Smartknower-MajorProject/blob/main/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
df = pd.read_csv('/content/tripadvisor_hotel_reviews.csv')
df

Review  Rating
0      nice hotel expensive parking got good deal sta...       4
1      ok nothing special charge diamond member hilto...       2
2      nice rooms not 4* experience hotel monaco seat...       3
3      unique, great stay, wonderful time hotel monac...       5
4      great stay great stay, went seahawk game aweso...       5
...                                                  ...     ...
20486  best kept secret 3rd time staying charm, not 5...       5
20487  great location price view hotel great quick pl...       4
20488  ok just looks nice modern outside, desk staff ...       2
20489  hotel theft ruined vacation hotel opened sept ...       1
20490  people talking, ca n't believe excellent ratin...       2

[20491 rows x 2 columns]

In [50]:
import numpy as np            

In [51]:
!pip install contractions

In [52]:
import contractions
def con(text):
  expand=contractions.fix(text)
  return expand  

In [53]:
import re
def remove_sp(text):
  pattern=r'[^A-Za-z\s]'
  text=re.sub(pattern,'',text)
  return text

In [54]:
from nltk.tokenize.toktok import ToktokTokenizer
tokenizer=ToktokTokenizer()

In [55]:
def remove_stopwords(text):
  tokens=tokenizer.tokenize(text)
  tokens=[token.strip() for token in tokens]
  filtered_tokens=[token for token in tokens if token not in stopword_list]
  filtered_text=' '.join(filtered_tokens)
  return filtered_text 

In [56]:
import nltk
nltk.download('stopwords')
stopword_list=nltk.corpus.stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [57]:
df.Review=df.Review.apply(lambda x:x.lower())
df.Review=df.Review.apply(con)
df.Review=df.Review.apply(remove_sp)
df.Review=df.Review.apply(remove_stopwords)

In [58]:
df.head

<bound method NDFrame.head of                                                   Review  Rating
0      nice hotel expensive parking got good deal sta...       4
1      ok nothing special charge diamond member hilto...       2
2      nice rooms experience hotel monaco seattle goo...       3
3      unique great stay wonderful time hotel monaco ...       5
4      great stay great stay went seahawk game awesom...       5
...                                                  ...     ...
20486  best kept secret rd time staying charm star ca...       5
20487  great location price view hotel great quick pl...       4
20488  ok looks nice modern outside desk staff nt par...       2
20489  hotel theft ruined vacation hotel opened sept ...       1
20490  people talking ca nt believe excellent ratings...       2

[20491 rows x 2 columns]>

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(
                      use_idf=True,
                      norm='l2',
                      smooth_idf=True
                      )

y = df.Rating.values
x=tfidf.fit_transform(df['Review'].values.astype('U'))

# document-term matrix

In [60]:
# Input and Output
x = df['Review'].values
y = df['Rating'].values

In [61]:
y

array([4, 2, 3, ..., 2, 1, 2])

In [62]:
# Split the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0)

In [63]:
print(x_train.shape)
print(x_test.shape)

(15368,)
(5123,)


In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [66]:
vect = TfidfVectorizer(stop_words='english')
x_train_vect = vect.fit_transform(x_train)
x_test_vect = vect.transform(x_test)

# document-term matrix

In [67]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train_vect,y_train) # Map input with output

# ValueError: could not convert string to float.

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [68]:
y_pred = model.predict(x_test_vect)

In [69]:
from sklearn.metrics import accuracy_score,classification_report
accuracy_score(y_pred,y_test)

0.6238532110091743

In [70]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           1       0.58      0.73      0.64       266
           2       0.43      0.46      0.44       417
           3       0.14      0.52      0.21       153
           4       0.56      0.52      0.54      1640
           5       0.85      0.71      0.77      2647

    accuracy                           0.62      5123
   macro avg       0.51      0.59      0.52      5123
weighted avg       0.68      0.62      0.65      5123



In [74]:
test = df['Review'][0]

In [72]:
df['Rating'][0]

4

In [73]:
test = vect.transform([df['Review'][0]])
model.predict(test)

array([4])

In [ ]:
# Pipeline = Combining two or more estimators
# Joblib = Saving the model
# Streamlit = Webapp
# Heroku = CLoud service to deploy webapp


In [75]:
# Pipeline = CountVectorizer+SVM
# https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html

#Method 2
from sklearn.pipeline import make_pipeline
text_model = make_pipeline(TfidfVectorizer(),SVC())

text_model.fit(x_train,y_train)

y_pred = text_model.predict(x_test)
y_pred

# Sequentially apply a list of transforms and a final estimator. Intermediate steps of the pipeline must be ‘transforms’, that is, they must implement fit and transform methods. 
# The final estimator only needs to implement fit.

array([2, 4, 5, ..., 5, 5, 5])

In [76]:
text_model.predict([df['Review'][0]])

array([4])

In [77]:
text_model

Pipeline(memory=None,
         steps=[('tfidfvectorizer',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('svc',
                 SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None,
                     coef0=0.0, decision_function_shape=

In [78]:
import joblib
joblib.dump(text_model,'sentiment_analysis')

# Saving pipeline in a file

['sentiment_analysis']

In [79]:
import sys
sys.version

'3.7.10 (default, May  3 2021, 02:48:31) \n[GCC 7.5.0]'